# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 09:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='Tekst',
            new_name='text',
        ),
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(default='tekst', max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='n_gram',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
