# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170609_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='types',
            field=models.CharField(choices=[('Ilukirjandus', 'Ilukirjandus'), ('Esseistika', 'Esseistika'), ('Epistolaarne kirjandus', 'Epistolaarne kirjandus'), ('Memuaristika', 'Memuaristika'), ('Kroonikakirjandus', 'Kroonikakirjandus'), ('Teaduskirjandus', 'Teaduskirjandus'), ('Populaarteaduslik', 'Populaarteaduslik'), ('Faktikirjandus', 'Faktikirjandus'), ('Teabekirjandus', 'Teabekirjandus'), ('Õppekirjandus', 'Õppekirjandus'), ('Teatmekirjandus', 'Teatmekirjandus'), ('Tarbekirjandus', 'Tarbekirjandus'), ('Kommertsteksti', 'Kommertsteksti'), ('Poliitiline kirjandus', 'Poliitiline kirjandus'), ('Vaimulik kirjandus', 'Vaimulik kirjandus'), ('Epitaafid', 'Epitaafid'), ('Muusika literatuur', 'Muusika literatuur')], default='Ilukirjandus', max_length=100),
        ),
    ]
