# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_content_types'),
        ('website', '0002_auto_20170609_0902'),
    ]

    operations = [
    ]
